[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
openjack = "2AWsuApMg1gr4e9Ybc5Uji5cJnjYDjYaqQzjn6s6draX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/openjack"]

[scripts]
test = "cargo test -p openjack"
